name: Tests-CI

on:
  pull_request:
    branches: main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_weather
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        node-version: [15.x]

    steps:
     - name: Clone repo
       uses: actions/checkout@v2

    #  - name: Install deps
    #    run: npm i && npm i cross-env

    #  - name: Running tests for API
    #    run: npm run test

     - name: Print ENV
       run: echo ${{ env.POSTGRES_HOST }}

    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      ACCESS_TOKEN_SECRET: SECRET_ACCESS
      REFRESH_TOKEN_SECRET: SECRET_REFRESH
      API_KEY: ${{ secrets.API_KEYS }}
