name: Tests-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
     - name: Clone repo
       uses: actions/checkout@v2

     - name: Use Node.js ${{ matrix.node-version }}
       run: $ echo ${GITHUB_REF##*/}

     - name: Running tests for API
       run: npm run test
      
